(() => {
  'use strict'

  const LEVELS = [
    { id:1, name:'哈吉米，启动！', description:'先别急着卡关，这关主要防止你开局退游。', gameSubtitle:'现在后悔还来得及。', optimalSteps:51, optimalPushes:11, solution:'URDRRDDRDDLLULLDLURRRDLLRRRRUULUULLDDUURRDDRDDLLULL', map:[[0,1,1,1,1,0,0,0],[0,1,2,2,1,1,1,0],[0,1,5,4,2,2,1,0],[1,1,1,2,1,2,1,1],[1,3,1,2,1,2,2,1],[1,3,4,2,2,1,2,1],[1,3,2,2,2,4,2,1],[1,1,1,1,1,1,1,1]] },
    { id:2, name:'猫猫祟祟', description:'看似乱推，实则每一步都像蓄谋已久。', gameSubtitle:'已经开始鬼鬼祟祟了。', optimalSteps:10, optimalPushes:6, solution:'DULLRUUDRR', map:[[0,0,1,1,1,0,0,0],[0,0,1,3,1,0,0,0],[0,0,1,2,1,1,1,1],[1,1,1,4,2,4,3,1],[1,3,2,4,5,1,1,1],[1,1,1,1,4,1,0,0],[0,0,0,1,3,1,0,0],[0,0,0,1,1,1,0,0]] },
    { id:3, name:'不是，猫们？', description:'地图已经开始针对你了，建议脑子也上线。', gameSubtitle:'不是，猫们？真要这么走？', optimalSteps:51, optimalPushes:14, solution:'UUDDLLDDRRUUDDRRULDLLLUURRURDLLLDDRRUURULDDDRUULLUU', map:[[0,0,1,1,1,1,0,0],[0,0,1,3,3,1,0,0],[0,1,1,2,3,1,1,0],[0,1,2,2,4,3,1,0],[1,1,2,2,5,4,1,1],[1,2,2,1,4,4,2,1],[1,2,2,2,2,2,2,1],[1,1,1,1,1,1,1,1]] },
    { id:4, name:'有点脏了', description:'场面已经失控，但哈吉米觉得问题不大。', gameSubtitle:'今天必须有人把这里收拾了。', optimalSteps:61, optimalPushes:20, solution:'LUUUULURRDLDDDDLLUURLDDRRUUUURULDDDDDRRRUULUDLUDRRDDLLLUUURUL', map:[[0,1,1,1,1,1,1,0],[0,1,3,2,3,3,1,0],[0,1,3,2,4,3,1,0],[1,1,1,2,2,4,1,1],[1,2,4,2,2,4,2,1],[1,2,1,4,1,1,2,1],[1,2,2,2,5,2,2,1],[1,1,1,1,1,1,1,1]] }
  ]

  const STORAGE_KEY = 'hajimiSokobanProgressV1'
  const DIRS = { U:{dr:-1,dc:0}, D:{dr:1,dc:0}, L:{dr:0,dc:-1}, R:{dr:0,dc:1} }
  const ARROWS = { U:'↑', D:'↓', L:'←', R:'→' }
  const app = document.getElementById('app')
  const toastEl = document.getElementById('toast')
  let toastTimer = null
  let current = { view:'home', levelId:null, expanded:null }
  let runtime = null, history = [], steps = 0, pushes = 0, finished = false, images = null

  function keyOf(r,c){ return `${r},${c}` }
  function parseMap(map){
    const floors=new Set(),walls=new Set(),goals=new Set(),boxes=new Set(); let player={row:0,col:0}
    map.forEach((line,row)=>line.forEach((value,col)=>{ const k=keyOf(row,col); if(value===1){walls.add(k);return} if([2,3,4,5].includes(value))floors.add(k); if(value===3)goals.add(k); else if(value===4)boxes.add(k); else if(value===5)player={row,col} }))
    return {floors,walls,goals,boxes,player}
  }
  function snapshot(state){ return { player:{...state.player}, boxes:Array.from(state.boxes) } }
  function restore(state,saved){ state.player={...saved.player}; state.boxes=new Set(saved.boxes) }
  function tryMove(state,direction){ const d=DIRS[direction]; if(!d)return{moved:false,pushed:false}; const nr=state.player.row+d.dr,nc=state.player.col+d.dc,nk=keyOf(nr,nc); if(!state.floors.has(nk))return{moved:false,pushed:false}; let pushed=false; if(state.boxes.has(nk)){ const br=nr+d.dr,bc=nc+d.dc,bk=keyOf(br,bc); if(!state.floors.has(bk)||state.boxes.has(bk))return{moved:false,pushed:false}; state.boxes.delete(nk);state.boxes.add(bk);pushed=true } state.player={row:nr,col:nc}; return{moved:true,pushed} }
  function isSolved(state){ if(state.boxes.size!==state.goals.size)return false; for(const b of state.boxes)if(!state.goals.has(b))return false; return true }
  function emptyProgress(){ return {version:1,levels:{1:{passed:false,bestSteps:null,bestPushes:null},2:{passed:false,bestSteps:null,bestPushes:null},3:{passed:false,bestSteps:null,bestPushes:null},4:{passed:false,bestSteps:null,bestPushes:null}}} }
  function getProgress(){ try{ const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'); const base=emptyProgress(); if(!raw||typeof raw!=='object')return base; for(let i=1;i<=4;i++){const s=raw.levels&&raw.levels[i];if(!s)continue;base.levels[i]={passed:Boolean(s.passed),bestSteps:Number.isFinite(s.bestSteps)?s.bestSteps:null,bestPushes:Number.isFinite(s.bestPushes)?s.bestPushes:null}} return base }catch{return emptyProgress()} }
  function saveProgress(p){ try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}catch{} }
  function saveLevelResult(levelId,s,push){ const prog=getProgress(),old=prog.levels[levelId]||{passed:false,bestSteps:null,bestPushes:null}; const isNewRecord=old.bestSteps===null||s<old.bestSteps; prog.levels[levelId]={passed:true,bestSteps:old.bestSteps===null?s:Math.min(old.bestSteps,s),bestPushes:old.bestPushes===null?push:Math.min(old.bestPushes,push)}; saveProgress(prog); return{isNewRecord,bestSteps:prog.levels[levelId].bestSteps} }
  function showToast(text){ toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),1300) }
  function asset(path){ return `./assets/${path}` }
  function navigate(view,levelId=null){ current={view,levelId,expanded:null}; location.hash=view==='home'?'home':view==='game'?`game/${levelId}`:'solutions'; render() }
  function syncFromHash(){ const h=location.hash.replace(/^#/,''); if(h.startsWith('game/')){ const id=Math.min(4,Math.max(1,Number(h.split('/')[1])||1)); current={view:'game',levelId:id,expanded:null} } else if(h==='solutions')current={view:'solutions',levelId:null,expanded:null}; else current={view:'home',levelId:null,expanded:null}; render() }

  function previewHTML(map){ return map.flatMap(row=>row.map(v=>`<div class="preview-cell v${v}"></div>`)).join('') }
  function renderHome(){ const prog=getProgress(); let passedCount=0; const cards=LEVELS.map(level=>{ const saved=prog.levels[level.id]||{},passed=!!saved.passed,perfect=passed&&saved.bestSteps===level.optimalSteps; if(passed)passedCount++; const status=perfect?'★ 猫界标准答案':passed?`✓ 已处理 · BEST ${saved.bestSteps}`:'尚未作案'; return `<article class="level-card" data-level="${level.id}"><div class="level-top"><span class="level-number">0${level.id}</span><span class="level-status ${perfect?'perfect':passed?'passed':''}">${status}</span></div><div class="preview">${previewHTML(level.map)}</div><div class="level-name">${level.name}</div><div class="level-desc">${level.description}</div></article>` }).join(''); const first=LEVELS.find(l=>!(prog.levels[l.id]||{}).passed); const cont=first?first.id:4; app.innerHTML=`<section><div class="hero-card"><div class="hero-copy"><div class="eyebrow">HAJIMI PUSH!</div><h1 class="hero-title">哈吉米<br>推什么推</h1><div class="hero-desc">黑猫已就位，剩下的麻烦归你。</div><button class="hero-btn" id="continueBtn">${passedCount>0?'继续营业':'开始作案'} <span>→</span></button></div><img class="hero-cat" src="${asset('hajimi/hero.png')}" alt="哈吉米"></div><div class="section-head"><div class="section-title">今晚处理这些烂摊子</div><div class="section-meta">4 个现场</div></div><div class="level-grid">${cards}</div><div class="progress-card"><div class="progress-row"><span>作案进度</span><span>${passedCount} / 4</span></div><div class="progress-dots">${LEVELS.map(l=>`<span class="dot ${(prog.levels[l.id]||{}).passed?'done':''}"></span>`).join('')}</div><div class="progress-copy">${passedCount<4?'现场不多，麻烦不少。':'今晚的烂摊子已经全部处理。'}</div></div><div class="solution-entry" id="solutionsBtn"><div><div class="solution-entry-title">标准作案路线</div><div class="solution-entry-desc">通关后才能名正言顺偷看。</div></div><div>→</div></div></section>`; document.getElementById('continueBtn').onclick=()=>navigate('game',cont); document.querySelectorAll('.level-card').forEach(el=>el.onclick=()=>navigate('game',Number(el.dataset.level))); document.getElementById('solutionsBtn').onclick=()=>navigate('solutions') }

  async function preload(){ if(images)return images; const names={player:'hajimi/player.png',push:'hajimi/player-push.png',can:'game/can.png',bowl:'game/bowl.png',wall:'game/wall.png',clear:'hajimi/clear.png',compute:'hajimi/compute.png'}; images={}; await Promise.all(Object.entries(names).map(([k,p])=>new Promise(resolve=>{ const img=new Image();img.onload=()=>{images[k]=img;resolve()};img.onerror=()=>resolve();img.src=asset(p)}))); return images }
  function resizeCanvas(canvas){ const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1); const px=Math.round(rect.width*dpr); if(canvas.width!==px||canvas.height!==px){canvas.width=px;canvas.height=px} const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,size:rect.width,cell:rect.width/8} }
  function drawBoard(pushImg=false){ const canvas=document.getElementById('gameCanvas'); if(!canvas||!runtime)return; const {ctx,size,cell}=resizeCanvas(canvas),state=runtime; ctx.clearRect(0,0,size,size);ctx.fillStyle='#DED8CC';ctx.fillRect(0,0,size,size);for(let row=0;row<8;row++)for(let col=0;col<8;col++){const x=col*cell,y=row*cell,k=keyOf(row,col),floor=state.floors.has(k),wall=state.walls.has(k);if(floor||wall){ctx.fillStyle=(row+col)%2===0?'#F5F1E8':'#ECE6DB';ctx.fillRect(x,y,cell+.5,cell+.5);ctx.strokeStyle='rgba(126,116,99,.10)';ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,cell-1,cell-1)}if(wall){if(images&&images.wall){const m=cell*.075;ctx.drawImage(images.wall,x+m,y+m,cell-m*2,cell-m*2)}else{ctx.strokeStyle='#746B60';ctx.strokeRect(x+cell*.1,y+cell*.1,cell*.8,cell*.8)}}} state.goals.forEach(k=>{const [r,c]=k.split(',').map(Number),x=c*cell,y=r*cell;if(images&&images.bowl){const w=cell*.72,h=cell*.5;ctx.drawImage(images.bowl,x+(cell-w)/2,y+(cell-h)/2+cell*.08,w,h)}else{ctx.beginPath();ctx.arc(x+cell/2,y+cell/2,cell*.23,0,Math.PI*2);ctx.strokeStyle='#AFC83F';ctx.lineWidth=2;ctx.stroke()}}); state.boxes.forEach(k=>{const [r,c]=k.split(',').map(Number),x=c*cell,y=r*cell;if(images&&images.can){const w=cell*.7,h=cell*.58;ctx.drawImage(images.can,x+(cell-w)/2,y+(cell-h)/2,w,h)}else{ctx.fillStyle='#F1C84B';ctx.beginPath();ctx.arc(x+cell/2,y+cell/2,cell*.22,0,Math.PI*2);ctx.fill()}if(state.goals.has(k)){const bx=x+cell*.75,by=y+cell*.25;ctx.fillStyle='#D5ED55';ctx.beginPath();ctx.arc(bx,by,cell*.12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#22261A';ctx.font=`bold ${Math.max(8,cell*.18)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('✓',bx,by)}}); const p=state.player,x=p.col*cell,y=p.row*cell,img=pushImg&&images&&images.push?images.push:images&&images.player;if(img){const w=cell*.9,h=cell*.84;ctx.drawImage(img,x+(cell-w)/2,y+(cell-h)/2,w,h)}else{ctx.fillStyle='#171A20';ctx.beginPath();ctx.arc(x+cell/2,y+cell/2,cell*.33,0,Math.PI*2);ctx.fill()} }
  function setStats(){ const s=document.getElementById('steps');if(s)s.textContent=steps;const p=document.getElementById('pushes');if(p)p.textContent=pushes }
  function handleMove(dir){ if(finished||current.view!=='game')return; const before=snapshot(runtime),res=tryMove(runtime,dir);if(!res.moved)return;history.push({state:before,steps,pushes});steps++;if(res.pushed)pushes++;setStats();drawBoard(res.pushed);if(res.pushed)setTimeout(()=>drawBoard(false),120);if(isSolved(runtime)){finished=true;setTimeout(finishLevel,220)} }
  function undo(){ if(finished)return;const last=history.pop();if(!last){showToast('还没走，先别后悔。');return}restore(runtime,last.state);steps=last.steps;pushes=last.pushes;setStats();drawBoard(false) }
  function reset(){ const level=LEVELS[current.levelId-1];runtime=parseMap(level.map);history=[];steps=0;pushes=0;finished=false;setStats();drawBoard(false);showToast('当无事发生。') }
  function finishLevel(){ const level=LEVELS[current.levelId-1],result=saveLevelResult(level.id,steps,pushes),diff=steps-level.optimalSteps; let comment='建议不要复盘，活着出来就行。';if(diff===0)comment='你和哈吉米共用一个脑回路。';else if(diff<=5)comment='差一点成为黑猫指定大脑。';else if(diff<=15)comment='路线有点自由，但问题解决了。'; const mask=document.createElement('div');mask.className='complete-mask';mask.innerHTML=`<div class="complete-card"><img class="complete-cat" src="${asset('hajimi/clear.png')}" alt=""><div class="complete-kicker">${result.isNewRecord?'NEW RECORD':''}</div><div class="complete-title">收拾完了，<br>但哈吉米不认账。</div><div class="complete-stats"><div class="complete-stat"><span class="complete-label">步数</span><span class="complete-value">${steps}</span></div><div class="complete-stat"><span class="complete-label">推动</span><span class="complete-value">${pushes}</span></div><div class="complete-stat"><span class="complete-label">最优</span><span class="complete-value" style="color:var(--accent)">${level.optimalSteps}</span></div></div><div class="complete-comment">${comment}</div><button class="complete-main" id="nextBtn">${level.id<4?'下一摊':'返回现场'}</button><div class="complete-links"><span id="replayBtn">再演一遍</span><span class="accent-link" id="solutionBtn">查看标准作案路线 →</span></div></div>`;document.body.appendChild(mask);document.getElementById('nextBtn').onclick=()=>{mask.remove();level.id<4?navigate('game',level.id+1):navigate('home')};document.getElementById('replayBtn').onclick=()=>{mask.remove();reset()};document.getElementById('solutionBtn').onclick=()=>{mask.remove();current={view:'solutions',expanded:level.id};location.hash='solutions';renderSolutions(level.id)} }
  function renderGame(){ const level=LEVELS[current.levelId-1],saved=(getProgress().levels[level.id]||{});runtime=parseMap(level.map);history=[];steps=0;pushes=0;finished=false;app.innerHTML=`<div class="topbar"><button class="back" id="backBtn">‹</button><div class="brand-mini">HAJIMI PUSH!</div><span></span></div><div class="page-heading"><span class="game-index">0${level.id} / 04</span><div class="game-title">${level.name}</div><div class="game-subtitle">${level.gameSubtitle}</div></div><div class="stats-card"><div class="stat"><div class="stat-label">步数</div><div class="stat-value" id="steps">0</div></div><div class="divider"></div><div class="stat"><div class="stat-label">推动</div><div class="stat-value" id="pushes">0</div></div><div class="divider"></div><div class="stat"><div class="stat-label">最佳</div><div class="stat-value">${Number.isFinite(saved.bestSteps)?saved.bestSteps:'--'}</div></div></div><div class="board-shell" id="boardShell"><canvas id="gameCanvas"></canvas></div><div class="gesture-hint">可以点猫爪遥控，也可以直接在棋盘上滑；电脑还支持方向键 / WASD。</div><div class="control-card"><div class="control-copy"><span class="control-title">猫爪遥控</span><span class="control-desc">方向明确，责任自负。</span></div><div class="dpad"><button class="dkey d-up" data-dir="U">↑</button><button class="dkey d-left" data-dir="L">←</button><div class="dcenter">🐾</div><button class="dkey d-right" data-dir="R">→</button><button class="dkey d-down" data-dir="D">↓</button></div></div><div class="actions"><button class="action dark" id="undoBtn">撤回一下</button><button class="action ghost" id="resetBtn">这把重开</button></div>`;document.getElementById('backBtn').onclick=()=>navigate('home');document.querySelectorAll('.dkey').forEach(b=>b.onclick=()=>handleMove(b.dataset.dir));document.getElementById('undoBtn').onclick=undo;document.getElementById('resetBtn').onclick=reset; const shell=document.getElementById('boardShell');let start=null;shell.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};shell.setPointerCapture?.(e.pointerId)});shell.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;handleMove(Math.abs(dx)>Math.abs(dy)?(dx>0?'R':'L'):(dy>0?'D':'U'))});preload().then(()=>drawBoard(false));requestAnimationFrame(()=>drawBoard(false)) }

  function renderSolutions(focus=null){ const prog=getProgress();let passed=0;const expanded=focus||current.expanded;const cards=LEVELS.map(level=>{const saved=prog.levels[level.id]||{},ok=!!saved.passed;if(ok)passed++;const open=expanded===level.id&&ok;return `<article class="route-card ${ok?'':'locked'}"><div class="route-summary" data-level="${level.id}"><div class="route-left"><div class="route-num">0${level.id}</div><div><div class="route-name">${level.name}</div><div class="route-state">${ok?`已解锁 · 你的最佳 ${Number.isFinite(saved.bestSteps)?saved.bestSteps:'--'} 步`:'你都没过，还想看答案？'}</div></div></div><div class="route-toggle">${ok?(open?'收起 ↑':'查看 ↓'):'LOCK'}</div></div>${open?`<div class="route-detail"><div class="route-metrics"><div class="metric"><div class="metric-label">理论最少</div><div class="metric-value">${level.optimalSteps} 步</div></div><div class="metric"><div class="metric-label">该路线推动</div><div class="metric-value">${level.optimalPushes} 次</div></div></div><div class="route-note">从第 1 步开始依次执行：</div><div class="move-grid">${level.solution.split('').map(d=>`<span class="move-chip">${ARROWS[d]}</span>`).join('')}</div><div class="route-foot">最优解按移动步数定义；如果只追求最少推动次数，可能得到另一条路线。</div></div>`:''}</article>`}).join('');app.innerHTML=`<div class="topbar"><button class="back" id="backBtn">‹</button><div class="brand-mini">HAJIMI ROUTE BOOK</div><span></span></div><div class="page-heading"><span class="eyebrow">HAJIMI ROUTE BOOK</span><div class="game-title">标准作案路线</div><div class="game-subtitle">以下内容包含严重剧透。</div></div><div class="compute-card"><img class="compute-cat" src="${asset('hajimi/compute.png')}" alt=""><div class="compute-copy"><div class="compute-title">哈吉米已完成猫爪运算</div><div class="compute-desc">四关均按“每移动一格记 1 步”计算理论最少步数。</div></div></div><div class="route-list">${cards}</div><div class="footer">已解锁 ${passed} / 4 · 不通关，不剧透。</div>`;document.getElementById('backBtn').onclick=()=>navigate('home');document.querySelectorAll('.route-summary').forEach(el=>el.onclick=()=>{const id=Number(el.dataset.level),saved=prog.levels[id]||{};if(!saved.passed){showToast('你都没过，还想看答案？');return}current.expanded=current.expanded===id?null:id;renderSolutions()}) }
  function render(){ if(current.view==='home')renderHome();else if(current.view==='game')renderGame();else renderSolutions() }

  window.addEventListener('keydown',e=>{ if(current.view!=='game')return; const map={ArrowUp:'U',w:'U',W:'U',ArrowDown:'D',s:'D',S:'D',ArrowLeft:'L',a:'L',A:'L',ArrowRight:'R',d:'R',D:'R'}; const dir=map[e.key]; if(dir){e.preventDefault();handleMove(dir)} })
  window.addEventListener('resize',()=>{ if(current.view==='game')drawBoard(false) })
  window.addEventListener('hashchange',syncFromHash)
  if(!location.hash)location.hash='home'; else syncFromHash()
})();
